apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: minio
spec:
  selector:
    matchLabels:
      app: minio
  template:
    metadata:
      labels:
        app: minio
    spec:
      containers:
        - name: minio
          image: minio/minio
          ports:
            - containerPort: 9000
            - containerPort: 9001
          command:
            - minio
            - server
            - /data
            - --console-address
            - :9001
          volumeMounts:
            - name: minio
              mountPath: /data
          envFrom:
            - secretRef:
                name: minio-secrets
      volumes:
        - name: minio
          persistentVolumeClaim:
            claimName: minio
