apiVersion: v1
kind: Secret
metadata:
  name: mariadb-secret
  labels:
    k8s.mariadb.com/watch: ""
stringData:
  password: password
  root-password: password
# apiVersion: external-secrets.io/v1
# kind: ExternalSecret
# metadata:
#   name: mariadb-secret
#   annotations:
#     k8s.mariadb.com/watch: ""
# spec:
#   refreshPolicy: Periodic
#   refreshInterval: 1h
