apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: minio
spec:
  selector:
    matchLabels:
      app: minio
  template:
    metadata:
      labels:
        app: minio
    spec:
      containers:
        - name: minio
          image: minio/minio
          ports:
          - containerPort: 9000
          - containerPort: 9001
          command:
          - minio
          - server
          - /data
          - --console-address
          - :9001
          volumeMounts:
            - name: minio
              mountPath: /data
          envFrom:
            - secretRef:
                name: minio-secrets
      volumes:
      - name: minio
        persistentVolumeClaim:
          claimName: minio
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minio
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: standard
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: Service
metadata:
  name: minio-console
spec:
  type: NodePort
  selector:
    app: minio
  ports:
  - port: 9001
    nodePort: 30008
---
apiVersion: v1
kind: Service
metadata:
  name: minio
spec:
  selector:
    app: minio
  ports:
  - port: 9000
---
apiVersion: v1
kind: Secret
metadata:
  name: minio-secrets
stringData:
  MINIO_ROOT_USER: admin
  MINIO_ROOT_PASSWORD: password
