kind: HTTPRoute
apiVersion: gateway.networking.k8s.io/v1beta1
metadata:
  name: wordpress
spec:
  parentRefs:
    - kind: Gateway
      name: external-http
  hostnames:
    - "wordpress.test"
  rules:
    - backendRefs:
        - name: wordpress
          port: 80
---
apiVersion: networking.gke.io/v1
kind: HealthCheckPolicy
metadata:
  name: wordpress-healthcheck
spec:
  default:
    checkIntervalSec: 30
    timeoutSec: 5
    healthyThreshold: 1
    unhealthyThreshold: 2
    config:
      type: HTTP
      httpHealthCheck:
        port: 80
        requestPath: /
  targetRef:
    group: ""
    kind: Service
    name: wordpress
