apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/mariadb
  - ../../base/redis
  - ../../base/wordpress
patches:
  - path: patches/ingress.yaml
    target:
      group: gateway.networking.k8s.io
      version: v1beta1
      kind: HTTPRoute
      name: wordpress