apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpmyadmin
spec:
  selector:
    matchLabels:
      app: phpmyadmin
  template:
    metadata:
      labels:
        app: phpmyadmin
    spec:
      containers:
        - name: phpmyadmin
          image: phpmyadmin/phpmyadmin
          ports:
          - containerPort: 80
          envFrom:
            - secretRef:
               name: phpmyadmin-secrets
---
apiVersion: v1
kind: Secret
metadata:
  name: phpmyadmin-secrets
stringData:
  PMA_HOST: mariadb
  MYSQL_ROOT_PASSWORD: verysecret
---
apiVersion: v1
kind: Service
metadata:
  name: phpmyadmin
spec:
  type: NodePort
  selector:
    app: phpmyadmin
  ports:
  - port: 80
    nodePort: 30009
