apiVersion: k8s.mariadb.com/v1alpha1
kind: Grant
metadata:
  name: wordpress
spec:
  mariaDbRef:
    name: wordpress-mariadb
  privileges:
  - ALL PRIVILEGES
  database: wordpress
  username: wordpress