apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mariadb
spec:
  selector:
    matchLabels:
      app: mariadb
  template:
    metadata:
      labels:
        app: mariadb
    spec:
      containers:
      - name: mariadb
        image: mariadb:10.11
        ports:
        - containerPort: 3306
        volumeMounts:
          - name: mariadb
            mountPath: /var/lib/mysql
        envFrom:
        - secretRef:
            name: mariadb-secrets
      volumes:
      - name: mariadb
        persistentVolumeClaim:
          claimName: mariadb
---
apiVersion: v1
kind: Secret
metadata:
  name: mariadb-secrets
stringData:
  MARIADB_USER: wordpress
  MARIADB_DATABASE: wordpress
  MARIADB_PASSWORD: secret
  MARIADB_RANDOM_ROOT_PASSWORD: verysecret
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mariadb
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: standard
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: Service
metadata:
  name: mariadb
spec:
  ports:
  - port: 3306
  selector:
    app: mariadb