# apiVersion: apps/v1
# kind: StatefulSet
# metadata:
#   name: mariadb
# spec:
#   selector:
#     matchLabels:
#       app: mariadb
#   template:
#     metadata:
#       labels:
#         app: mariadb
#     spec:
#       containers:
#       - name: mariadb
#         image: mariadb:10.11
#         ports:
#         - containerPort: 3306
#         volumeMounts:
#           - name: mariadb
#             mountPath: /var/lib/mysql
#         envFrom:
#         - secretRef:
#             name: mariadb-secrets
#       volumes:
#       - name: mariadb
#         persistentVolumeClaim:
#           claimName: mariadb
# ---
# apiVersion: v1
# kind: Secret
# metadata:
#   name: mariadb-secrets
# stringData:
#   MARIADB_USER: wordpress
#   MARIADB_DATABASE: wordpress
#   MARIADB_PASSWORD: secret
#   MARIADB_RANDOM_ROOT_PASSWORD: verysecret
# ---
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: mariadb
# spec:
#   accessModes:
#   - ReadWriteOnce
#   storageClassName: standard
#   resources:
#     requests:
#       storage: 2Gi
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: mariadb
# spec:
#   ports:
#   - port: 3306
#   selector:
#     app: mariadb
# ---
apiVersion: v1
kind: Secret
metadata:
  name: mariadb-secrets
  labels: 
    k8s.mariadb.com/watch: ''
stringData:
  MARIADB_PASSWORD: secret
  MARIADB_ROOT_PASSWORD: verysecret
---
apiVersion: k8s.mariadb.com/v1alpha1
kind: MariaDB
metadata:
  name: wordpress-mariadb
spec:
  rootPasswordSecretKeyRef:
    name: mariadb-secrets
    key: MARIADB_ROOT_PASSWORD
  storage:
    size: 1Gi
    storageClassName: standard
  replicas: 3
  replication:
    enabled: true
  primaryService:
    type: ClusterIP
  secondaryService:
    type: ClusterIP
---
apiVersion: k8s.mariadb.com/v1alpha1
kind: Database
metadata:
  name: wordpress
spec:
  mariaDbRef:
    name: wordpress-mariadb
---
apiVersion: k8s.mariadb.com/v1alpha1
kind: User
metadata:
  name: wordpress
spec:
  mariaDbRef:
    name: wordpress-mariadb
  passwordSecretKeyRef:
    name: mariadb-secrets
    key: MARIADB_PASSWORD
  maxUserConnections: 0
---
apiVersion: k8s.mariadb.com/v1alpha1
kind: Grant
metadata:
  name: wordpress
spec:
  mariaDbRef:
    name: wordpress-mariadb
  privileges:
  - ALL PRIVILEGES
  database: wordpress
  username: wordpress