apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
spec:
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
      - name: wordpress
        image: australia-southeast2-docker.pkg.dev/cplonline/cplonline-repository/wordpress-test:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 9000
        volumeMounts:
          - name: www-data
            mountPath: /var/www/html
        envFrom:
        - secretRef:
            name: wordpress-secrets
        - configMapRef:
            name: wordpress-env
        resources:
          requests:
            cpu: 200m
            memory: 128Mi
          limits:
            cpu: 400m
            memory: 256Mi

      - name: nginx
        image: nginx:1.27.4
        ports:
        - containerPort: 80
        volumeMounts:
          - name: www-data
            mountPath: /var/www/html
            readOnly: true
          - name: nginx
            mountPath: /etc/nginx/conf.d
            readOnly: true
        resources:
          requests:
            cpu: 50m
            memory: 64Mi
          limits:
            cpu: 100m
            memory: 128Mi

      volumes:
      - name: www-data
        emptyDir: {}
      - name: nginx
        configMap:
          name: wordpress-nginx
---
apiVersion: v1
kind: Service
metadata:
  name: wordpress
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: wordpress
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: www-data
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: standard
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: Secret
metadata:
  name: wordpress-secrets
stringData:
  WORDPRESS_DB_PASSWORD: secret
  WORDPRESS_AUTH_KEY: 7052c0863ea6269f44f0de17dc5c5879fdc02fd4
  WORDPRESS_SECURE_AUTH_KEY: e769128cb8376581e309a002466b1346910e8bd3
  WORDPRESS_LOGGED_IN_KEY: 9d3a12e80b9aa24c5a045f1f092e6ffb93f9823a
  WORDPRESS_NONCE_KEY: 2b4d5a460c2dde65380a47188b4b5ebbe723ab18
  WORDPRESS_AUTH_SALT: ba846d9aeefe6c706e5c93a750c1e4cd601e4408
  WORDPRESS_SECURE_AUTH_SALT: 667895c8d69089620e44a7f1a97b1ac3efc6e386
  WORDPRESS_LOGGED_IN_SALT: fcf21a031d5a54eab2c4749257829b0d2830ea7f
  WORDPRESS_NONCE_SALT: 6f3a1db3c6bd211d404e071a0ad1801c53e117dd
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: wordpress-env
data:
  WORDPRESS_DB_HOST: mariadb
  WORDPRESS_DB_USER: wordpress
  WORDPRESS_DB_NAME: wordpress
  WORDPRESS_CONFIG_EXTRA: |
    // WP-Stateless
    //define( 'WP_STATELESS_MEDIA_MODE', 'stateless' );
    //define( 'WP_STATELESS_MEDIA_BUCKET', getenv_docker('WORDPRESS_MEDIA_BUCKET', '') );
    //define( 'WP_STATELESS_MEDIA_JSON_KEY, getenv_docker('WORDPRESS_MEDIA_JSON_KEY', '') );

    define( 'JETPACK_DEV_DEBUG', true );
    define( 'WP_ENVIRONMENT_TYPE', 'development' );


    define( 'WP_AUTO_UPDATE_CORE', false );
    define( 'DISALLOW_FILE_EDIT', true );
    define( 'DISALLOW_FILE_MODS', true );

    define( 'S3_UPLOADS_BUCKET', 'wordpress' );
    define( 'S3_UPLOADS_REGION', 'world' );
    define( 'S3_UPLOADS_KEY', 'mIk6JTY9INyZES4CXSsS' );
    define( 'S3_UPLOADS_SECRET', 'HuGo2BBUFY7I32csQcjClzsaccQKYYUcey2oRTxl' );
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: wordpress-nginx
data:
  wordpress.conf: |
    server {
      listen 80 default_server;
      server_name _;
      root /var/www/html;
      index index.php index.html;
 
      location / {
        try_files $uri $uri/ /index.php?$args;
      }
 
      location ~ \.php$ {
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_pass 127.0.0.1:9000;
      }
    }
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: wordpress-ingress
spec:
  ingressClassName: nginx
  rules:
  - host: wordpress.test
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: wordpress
            port: 
              number: 80
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: wordpress
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: wordpress
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 80
