apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mariadb-operator
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    chart: mariadb-operator
    repoURL: "https://helm.mariadb.com/mariadb-operator"
    targetRevision: "0.38.0"
    helm:
      releaseName: mariadb-operator
  destination:
    server: "https://kubernetes.default.svc"
    namespace: mariadb
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mariadb-operator-crds
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    chart: mariadb-operator-crds
    repoURL: "https://helm.mariadb.com/mariadb-operator"
    targetRevision: "0.38.0"
    helm:
      releaseName: mariadb-operator-crds
  destination:
    server: "https://kubernetes.default.svc"
    namespace: mariadb
  syncPolicy:
    automated:
      prune: true
      selfHeal: true